# Generated by Django 4.2.2 on 2023-06-12 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan_sanctioning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_amount', models.FloatField(blank=True, default=0)),
                ('installment_no', models.IntegerField(blank=True, default=0)),
                ('monthly_installment_amount', models.FloatField(blank=True, default=0)),
                ('installment_expected_date', models.DateField(blank=True, default='2000-12-12')),
                ('installment_paid_date', models.DateField(blank=True, default='2000-12-12')),
                ('penalty_amount', models.FloatField(blank=True, default=0)),
                ('status', models.CharField(blank=True, choices=[('SELECT', 'SELECT'), ('OK', 'OK'), ('PENDING', 'PENDING'), ('LATE', 'LATE')], default='pending', max_length=100)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Installments', to='loan_sanctioning.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_doc', models.FileField(blank=True, default=0, upload_to='media/customer/disbursement')),
                ('payment_mode', models.CharField(blank=True, choices=[('SELECT', 'SELECT'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('IMPS', 'IMPS')], default=0, max_length=250)),
                ('net_disbursed_amount', models.FloatField(blank=True, default=0)),
                ('disbursed_to_account_no', models.CharField(blank=True, default=0, max_length=25)),
                ('receipt_doc', models.FileField(blank=True, default=0, upload_to='customer/disbursement')),
                ('status', models.CharField(blank=True, choices=[('SELECT', 'SELECT'), ('PENDING', 'PENDING'), ('DISBURST', 'DISBURST')], default=0, max_length=250)),
                ('response_timestamp', models.DateTimeField(auto_now=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Disbursements', to='loan_sanctioning.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Defaulter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_amount', models.FloatField(blank=True, default=0)),
                ('pending_since_date', models.DateField(blank=True, default='2000-12-12')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Defaulters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
